version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/shoop
hooks:
  BeforeInstall:
    - location: aws-codedeploy-helpers/BeforeInstall.sh
      timeout: 1000
      runas: root

  ApplicationStart:
    - location: aws-codedeploy-helpers/ApplicationStart.sh